In [6]:
import numpy as np
import pandas as pd
df = pd.read_excel("TASK1.xlsx")
print(df.head())

   Flow Depth, D [m]     SLOPE    CHARGE  Channel Width, B [m]  \
0               5.09  0.000204   34721.4                 306.0   
1               5.09  0.000098   15114.2                 261.0   
2               4.89  0.000077    7200.2                 258.0   
3               4.79  0.000066    5243.3                 257.0   
4               3.54  0.000348  125324.7                 449.2   

   Particle size, d [m]  Bed Form  
0              0.000978         2  
1              0.000978         2  
2              0.000978         2  
3              0.000978         2  
4              0.000978         2  


In [16]:
print("Dataset Shape:",df.shape)

Dataset Shape: (2548, 6)


In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2552 entries, 0 to 2551
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Flow Depth, D [m]     2548 non-null   float64
 1   SLOPE                 2548 non-null   float64
 2   CHARGE                2552 non-null   object 
 3   Channel Width, B [m]  2548 non-null   float64
 4   Particle size, d [m]  2548 non-null   float64
 5   Bed Form              2552 non-null   int64  
dtypes: float64(4), int64(1), object(1)
memory usage: 119.8+ KB
None


In [8]:
print(df.isnull().sum())

Flow Depth, D [m]       4
SLOPE                   4
CHARGE                  0
Channel Width, B [m]    4
Particle size, d [m]    4
Bed Form                0
dtype: int64


In [9]:
df = df.dropna()

In [10]:
print(df.isnull().sum())

Flow Depth, D [m]       0
SLOPE                   0
CHARGE                  0
Channel Width, B [m]    0
Particle size, d [m]    0
Bed Form                0
dtype: int64


In [12]:
print(df.describe())

       Flow Depth, D [m]         SLOPE  Channel Width, B [m]  \
count        2548.000000  2.548000e+03           2548.000000   
mean            2.718144  5.570980e-04            214.912591   
std             1.794157  6.710274e-04            100.474557   
min             0.080000  5.647930e-09             16.580000   
25%             1.570000  1.799793e-04            157.278756   
50%             2.265822  4.338692e-04            190.683165   
75%             3.492500  8.627090e-04            269.250000   
max            11.000000  2.209983e-02            625.500000   

       Particle size, d [m]     Bed Form  
count           2548.000000  2548.000000  
mean               0.011168     2.043171  
std                0.023022     0.230439  
min                0.000260     2.000000  
25%                0.001112     2.000000  
50%                0.002840     2.000000  
75%                0.013188     2.000000  
max                0.177230     6.000000  


In [13]:
print(df.dtypes)

Flow Depth, D [m]       float64
SLOPE                   float64
CHARGE                   object
Channel Width, B [m]    float64
Particle size, d [m]    float64
Bed Form                  int64
dtype: object


In [11]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [20]:
X = df[[
    "Flow Depth, D [m]",
    "SLOPE",
    "CHARGE",
    "Channel Width, B [m]",
    "Particle size, d [m]"
]]
y = df["Bed Form"]

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
mlp = MLPClassifier(
    hidden_layer_sizes=(50, 25),
    activation='relu',
    solver='adam',
    max_iter=1000,
    random_state=42
)
mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)

In [23]:
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy Score: 0.9647058823529412
Classification Report:
              precision    recall  f1-score   support

           2       0.96      1.00      0.98       492
           3       0.00      0.00      0.00        15
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         1

    accuracy                           0.96       510
   macro avg       0.24      0.25      0.25       510
weighted avg       0.93      0.96      0.95       510

Confusion Matrix:
[[492   0   0   0]
 [ 15   0   0   0]
 [  2   0   0   0]
 [  1   0   0   0]]


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
